defmodule CytaleWeb.Endpoint do
  @moduledoc """
  Phoenix endpoint for the Cytale backend (Bandit adapter).

  Carries the health check (`GET /health` → 200, no auth), the REST API scope
  and the WebSocket gateway mount point. Handlers for API and gateway land in
  later units (U8/U12/U10).
  """

  use Phoenix.Endpoint, otp_app: :cytale

  # NOTE: `Plug.ErrorHandler` is deliberately NOT used here. At the endpoint it
  # is the OUTERMOST wrapper, and `Phoenix.Endpoint.RenderErrors` catches the
  # exception INSIDE it, renders and sends a 500, then re-raises — after which
  # Plug.ErrorHandler sees `{:plug_conn, :sent}` and skips `handle_errors/2`
  # entirely. The callback was therefore never invoked and the 503 never sent
  # (verified by review: adapter received Phoenix's 500 with zero handler
  # invocations). It lives in `CytaleWeb.Router` instead, inside Phoenix's render
  # try, where the same review measured 503 + `retry-after: 5` reaching the
  # adapter. Plugs between here and the router keep Phoenix's 500 for an
  # exception; none of them touch the database.

  # Security headers FIRST (#35 P0-2): ahead of Plug.Static so the SPA
  # bundle itself carries the CSP/nosniff floor, not just the API routes.
  plug(CytaleWeb.Plugs.SecurityHeaders)

  # CORS for first-party shells served from another origin (the Tauri desktop
  # app). No-op for the deployed web client — same origin, no preflight. See
  # Cytale.Config.cors_allowed_origins/0.
  plug(CytaleWeb.Plugs.CORS)

  # Deployed web client (vite build output). Served at the root so the SPA,
  # the REST API (/api/v1/*), and the gateway (/gateway/websocket) share one
  # origin — no CORS, no split deployment. In dev the vite dev server owns
  # the frontend; this plug only mounts when the priv/static dir exists.
  plug(Plug.Static,
    at: "/",
    from: "priv/static",
    gzip: true,
    # `push-handler.js` MUST be listed. It is not generated by the build — it
    # lives in the SPA's public/ and is pulled into the service worker by
    # `importScripts`, so without an entry here the worker's own dependency
    # 404s and the push event has no handler at all. The 404 is a JSON error
    # body with `X-Content-Type-Options: nosniff`, so the browser refuses it as
    # a script: the failure presents as "notifications are silently never
    # delivered", with the service worker unregistered and nothing in any log.
    only: [
      "assets",
      "icons",
      "index.html",
      "manifest.json",
      "sw.js",
      "push-handler.js",
      # The boot-cover pair (2026-09-19): same trap as push-handler.js above —
      # a public/ file not in this list is skipped by Plug.Static and the SPA
      # fallback serves index.html as text/html, which the browser refuses as
      # a script (and the endpoint's own CSP then blocks nothing, because
      # nothing executed at all).
      "boot-theme.js",
      "boot-failsafe.js",
      # The version badge's release notes (scripts/release-notes.mjs writes
      # it into the SPA's public/ at build time). Same trap once more: left
      # off this list, the fetch gets index.html and the pane can only report
      # that the build carries no notes.
      "release-notes.json",
      "favicon.ico"
    ],
    only_matching: ["workbox"]
  )

  # Session/signed-socket secret handling is provided by Phoenix itself via
  # :secret_key_base from config.

  # The real client address behind Caddy (security Tier 2 #1): rewrites
  # conn.remote_ip from a TRUSTED proxy's X-Forwarded-For before anything
  # keys on it — every per-IP rate limit in the router and the gateway's
  # admission limiter read conn.remote_ip downstream of this.
  plug(CytaleWeb.Plugs.RemoteIp)

  plug(Plug.RequestId)
  plug(Plug.Telemetry, event_prefix: [:phoenix, :endpoint])

  # Body parser caps (C-5a): JSON requests cap at 2 MB (the legitimate max
  # is ~80 KB of embeds — anything larger is abuse, answered by Plug's 413);
  # multipart keeps its own cap (30 MB) — attachment uploads are multipart
  # and unaffected (the per-file cap on top is the attachment unit's 25 MB).
  plug(Plug.Parsers,
    parsers: [{:json, length: 2_000_000}, {:multipart, length: 30_000_000}],
    pass: ["*/*"],
    json_decoder: Jason
  )

  # U29: Deprecation/Sunset headers on endpoints registered in
  # :cytale, :deprecated_routes (see CytaleWeb.Plugs.Deprecation).
  plug(CytaleWeb.Plugs.Deprecation)

  plug(CytaleWeb.Router)
end
