/**
 * withAndroidReleaseSigning
 *
 * Makes `android/app/build.gradle` sign the **release** build with the Cytale
 * *upload* key instead of the React Native template's `debug.keystore`.
 *
 * Why a config plugin: `apps/mobile/android/` is CNG-generated and gitignored —
 * `npx expo prebuild --platform android` (and `--clean`) rewrites it from the
 * template. Any hand edit to `build.gradle` therefore survives exactly until the
 * next prebuild, which would silently put release builds back on the debug key.
 * This plugin re-applies the change on every prebuild, so the signing wiring
 * lives in version control (this file + `app.json`) rather than in generated code.
 *
 * What it does, in two mods:
 *
 *   1. `withAppBuildGradle` — points the release build type at a `release`
 *      signingConfig and injects that config (plus a guard) *above* the
 *      template's `android { }` block. The Gradle snippet declares nothing
 *      secret: at *build* time it resolves the keystore, alias and password, in
 *      this precedence order —
 *
 *        env var  →  credentials file  →  value baked into gradle.properties
 *                    (~/.cytale/...)      (keystore path + alias only)
 *
 *      The password is never written into the repository tree; it is read from
 *      `~/.cytale/android-upload-credentials.txt` (mode 600, outside git) or from
 *      `CYTALE_UPLOAD_KEY_PASSWORD`.
 *
 *   2. `withGradleProperties` — records the non-secret keystore path/alias as
 *      Gradle properties, so `./gradlew` runs (Android Studio, CI) work without
 *      an env-var dance. Env vars still override them.
 *
 * The guard is the point of the exercise: if the upload keystore or password is
 * missing, a **release** build fails immediately with an explanatory error. It
 * never falls back to `signingConfigs.debug`. Debug builds are unaffected.
 *
 * Config:
 *   CYTALE_UPLOAD_KEYSTORE      absolute path to the upload keystore
 *   CYTALE_UPLOAD_KEY_ALIAS     key alias inside that keystore
 *   CYTALE_UPLOAD_KEY_PASSWORD  store/key password (PKCS12: both are the same)
 *   CYTALE_UPLOAD_CREDENTIALS   path to the KEY=VALUE credentials file
 *
 * See docs/mobile-release.md.
 */

const os = require('os');
const path = require('path');
const fs = require('fs');

const {
  createRunOncePlugin,
  withAppBuildGradle,
  withGradleProperties,
  WarningAggregator,
} = require('expo/config-plugins');

const PLUGIN_NAME = 'withAndroidReleaseSigning';
const PLUGIN_VERSION = '1.0.0';

/** Markers around the block this plugin appends. Also the idempotency anchor. */
const MARKER_BEGIN = '// @generated begin cytale-upload-signing';
const MARKER_END = '// @generated end cytale-upload-signing';

/** Defaults: everything lives OUTSIDE the repository, in the owner's home dir. */
const DEFAULT_KEYSTORE_PATH = path.join(os.homedir(), '.cytale', 'android-upload.keystore');
const DEFAULT_CREDENTIALS_PATH = path.join(
  os.homedir(),
  '.cytale',
  'android-upload-credentials.txt',
);
const DEFAULT_KEY_ALIAS = 'cytale-upload';

/** Escape a value for a double-quoted Groovy string literal. */
function groovyString(value) {
  return String(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

/** Flat, conventional Gradle property name for the keystore path. */
const PROP_KEYSTORE_PATH = 'cytale.upload.keystorePath';
const PROP_KEY_ALIAS = 'cytale.upload.keyAlias';

/**
 * The Gradle block the plugin injects into android/app/build.gradle, right before
 * the template's `android { }` block. It has to sit *above* that block because
 * the template's `buildTypes.release.signingConfig` line (`signingConfig
 * signingConfigs.release`, rewritten by this plugin) resolves
 * `signingConfigs.release` while the file is being evaluated — so the config has
 * to exist by then.
 *
 * Resolution order for every value is `System.getenv(...)` first, so a shell
 * (`CYTALE_UPLOAD_KEYSTORE=... ./gradlew bundleRelease`) or the release script
 * can point a build at another keystore without re-running prebuild.
 */
function buildGradleSnippet(keystorePath, keyAlias) {
  return `
${MARKER_BEGIN}
// Release signing with the Cytale upload key.
// Generated by apps/mobile/plugins/withAndroidReleaseSigning.js — DO NOT EDIT
// this block by hand: it is rewritten on every \`npx expo prebuild --platform android\`.
// Edit the plugin (and apps/mobile/app.json) instead. See docs/mobile-release.md.
def cytaleUploadDefaultKeystorePath = "${groovyString(keystorePath)}"
def cytaleUploadDefaultKeyAlias = "${groovyString(keyAlias)}"

// Optional KEY=VALUE file holding the keystore path, alias and password. Kept
// outside the repository so the password never lands in a file git could see.
def cytaleUploadCredentialsFile = file(
        System.getenv("CYTALE_UPLOAD_CREDENTIALS") ?: "${groovyString(
          DEFAULT_CREDENTIALS_PATH,
        )}")
def cytaleUploadCredentials = [:]
if (cytaleUploadCredentialsFile.exists()) {
    cytaleUploadCredentialsFile.eachLine('UTF-8') { String line ->
        def trimmed = line.trim()
        if (trimmed && !trimmed.startsWith('#') && trimmed.contains('=')) {
            def entry = trimmed.split('=', 2)
            cytaleUploadCredentials[entry[0].trim()] = entry[1].trim()
        }
    }
}

def cytaleUploadKeystorePath =
        System.getenv("CYTALE_UPLOAD_KEYSTORE")
                ?: cytaleUploadCredentials["CYTALE_UPLOAD_KEYSTORE"]
                ?: (findProperty("${PROP_KEYSTORE_PATH}") ?: cytaleUploadDefaultKeystorePath)
def cytaleUploadKeyAlias =
        System.getenv("CYTALE_UPLOAD_KEY_ALIAS")
                ?: cytaleUploadCredentials["CYTALE_UPLOAD_KEY_ALIAS"]
                ?: (findProperty("${PROP_KEY_ALIAS}") ?: cytaleUploadDefaultKeyAlias)
def cytaleUploadKeyPassword =
        System.getenv("CYTALE_UPLOAD_KEY_PASSWORD")
                ?: cytaleUploadCredentials["CYTALE_UPLOAD_KEY_PASSWORD"]
                ?: ""
def cytaleUploadKeystore = file(cytaleUploadKeystorePath)

/**
 * Refuse to build a release artifact that is not signed with the upload key.
 * This is deliberately fatal: a debug-signed upload is unrecoverable on Play
 * (the version code is burned and the certificate is wrong), so the build must
 * stop rather than fall back to signingConfigs.debug.
 */
def cytaleAssertUploadSigning = {
    if (!cytaleUploadKeystore.exists()) {
        throw new GradleException("""
CYTALE RELEASE SIGNING IS NOT CONFIGURED: the upload keystore does not exist.

  keystore: \${cytaleUploadKeystorePath}

Refusing to build a release artifact, which would otherwise be signed with the
template debug key. Fix one of:
  * restore the keystore from backup to that path, or
  * set CYTALE_UPLOAD_KEYSTORE=/abs/path/to/upload.keystore, or
  * put CYTALE_UPLOAD_KEYSTORE=/abs/path/... in the credentials file.
See docs/mobile-release.md.
""")
    }
    if (!cytaleUploadKeyAlias?.trim()) {
        throw new GradleException(
                "CYTALE RELEASE SIGNING IS NOT CONFIGURED: no key alias " +
                "(set CYTALE_UPLOAD_KEY_ALIAS, or CYTALE_UPLOAD_KEY_ALIAS=... in the credentials file).")
    }
    if (!cytaleUploadKeyPassword?.trim()) {
        throw new GradleException("""
CYTALE RELEASE SIGNING IS NOT CONFIGURED: no keystore password.

  keystore: \${cytaleUploadKeystorePath}

The password is read from CYTALE_UPLOAD_KEY_PASSWORD or from
${groovyString(DEFAULT_CREDENTIALS_PATH)}
(neither is committed to git). See docs/mobile-release.md.
""")
    }
}

// Case 1: the release task is named on the command line — fail during
// configuration, before Gradle spins up any work.
if (gradle.startParameter.taskNames.any { it.toLowerCase().contains("release") }) {
    cytaleAssertUploadSigning()
}

// Case 2: a release task is reachable indirectly (e.g. \`./gradlew build\`) —
// fail once the task graph is known, still before anything is packaged.
gradle.taskGraph.whenReady { graph ->
    if (graph.allTasks.any { it.path.toLowerCase().contains("release") }) {
        cytaleAssertUploadSigning()
    }
}

// The upload-key signing config. Created through the container API rather than
// the \`signingConfigs { release { } }\` DSL sugar so it exists before the
// \`android { }\` block below references it.
def cytaleUploadSigningConfig = android.signingConfigs.maybeCreate("release")
cytaleUploadSigningConfig.storeFile = cytaleUploadKeystore
cytaleUploadSigningConfig.storePassword = cytaleUploadKeyPassword
cytaleUploadSigningConfig.keyAlias = cytaleUploadKeyAlias
cytaleUploadSigningConfig.keyPassword = cytaleUploadKeyPassword
${MARKER_END}
`;
}

/** Where the injected block goes: immediately before the template's android block. */
const ANDROID_BLOCK_ANCHOR = /^android \{/m;

/** Replace the release build type's debug signing with the upload-key config. */
function pointReleaseAtUploadKey(contents) {
  // In the template the release block is the only `release {` block and the only
  // one whose body mentions `signingConfig`, so this cannot hit the debug block.
  const releaseDebugSigning = /release\s*\{[^}]*?signingConfig\s+signingConfigs\.debug/;
  if (releaseDebugSigning.test(contents)) {
    return contents.replace(
      releaseDebugSigning,
      (match) => match.replace(/signingConfig\s+signingConfigs\.debug\s*$/, 'signingConfig signingConfigs.release'),
    );
  }
  if (/release\s*\{[^}]*?signingConfig\s+signingConfigs\.release/.test(contents)) {
    return contents; // already pointed at the upload key (idempotent re-run)
  }
  throw new Error(
    `${PLUGIN_NAME}: could not find "signingConfig signingConfigs.debug" inside the release ` +
      `build type of android/app/build.gradle. The Expo/React Native template changed shape; ` +
      `update this plugin — do not ship a release build until the release build type signs with ` +
      `signingConfigs.release.`,
  );
}

/** Drop a previously injected block, so re-running prebuild does not stack copies. */
function stripInjectedBlock(contents) {
  const start = contents.indexOf(MARKER_BEGIN);
  if (start === -1) return contents;
  const end = contents.indexOf(MARKER_END, start);
  if (end === -1) return contents.slice(0, start);
  return contents.slice(0, start) + contents.slice(end + MARKER_END.length);
}

/** Upsert a `key=value` entry in the Expo gradle.properties mod results. */
function upsertGradleProperty(properties, key, value) {
  const next = properties.filter((item) => !(item.type === 'property' && item.key === key));
  next.push({ type: 'property', key, value });
  return next;
}

function withAndroidReleaseSigning(config) {
  const keystorePath = process.env.CYTALE_UPLOAD_KEYSTORE || DEFAULT_KEYSTORE_PATH;
  const keyAlias = process.env.CYTALE_UPLOAD_KEY_ALIAS || DEFAULT_KEY_ALIAS;
  const credentialsPath = process.env.CYTALE_UPLOAD_CREDENTIALS || DEFAULT_CREDENTIALS_PATH;

  if (!fs.existsSync(keystorePath)) {
    WarningAggregator.addWarningAndroid(
      PLUGIN_NAME,
      `upload keystore not found at ${keystorePath}. Gradle will be generated correctly, but ` +
        `release builds will FAIL until the keystore exists (or CYTALE_UPLOAD_KEYSTORE is set). ` +
        `See docs/mobile-release.md.`,
    );
  }
  if (!fs.existsSync(credentialsPath) && !process.env.CYTALE_UPLOAD_KEY_PASSWORD) {
    WarningAggregator.addWarningAndroid(
      PLUGIN_NAME,
      `no credentials file at ${credentialsPath} and CYTALE_UPLOAD_KEY_PASSWORD is unset; ` +
        `release builds will FAIL rather than fall back to debug signing. See docs/mobile-release.md.`,
    );
  }

  config = withGradleProperties(config, (cfg) => {
    cfg.modResults = upsertGradleProperty(cfg.modResults, PROP_KEYSTORE_PATH, keystorePath);
    cfg.modResults = upsertGradleProperty(cfg.modResults, PROP_KEY_ALIAS, keyAlias);
    return cfg;
  });

  config = withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error(
        `${PLUGIN_NAME}: android/app/build.gradle is not Groovy; cannot inject release signing.`,
      );
    }
    let contents = stripInjectedBlock(cfg.modResults.contents);
    contents = pointReleaseAtUploadKey(contents);
    if (!ANDROID_BLOCK_ANCHOR.test(contents)) {
      throw new Error(
        `${PLUGIN_NAME}: could not find the \`android {\` block in android/app/build.gradle. ` +
          `The Expo/React Native template changed shape; update this plugin.`,
      );
    }
    const snippet = buildGradleSnippet(keystorePath, keyAlias);
    cfg.modResults.contents = contents.replace(
      ANDROID_BLOCK_ANCHOR,
      (anchor) => `${snippet}${anchor}`,
    );
    return cfg;
  });

  return config;
}

module.exports = createRunOncePlugin(withAndroidReleaseSigning, PLUGIN_NAME, PLUGIN_VERSION);
